[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.6

[window.padding]
x = 18
y = 15


[colors.cursor]
text = "#1d1f21"
cursor = "#e7c547"


[colors.selection]
text =  "#1d1f21"
background = "#b9ca4a"





