[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
user = "gargula"
command = "/usr/bin/Hyprland"

# Autologin
[initial_session]
user = "gargula"
command = "/usr/bin/Hyprland"


