#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II II IV

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           30
bspc config focused_border_color  "#30f090"

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Mouse Follow the Focus
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

wmname LG3D

# xmobar
$HOME/dotfiles/xmobar/launch-xmobar.sh

# trayer (tray icons)
$HOME/dotfiles/xmobar/launch-trayer.sh

# Auto start apps
$HOME/dotfiles/bspwm/autostart.sh &

