#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II II IV

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           30
bspc config focused_border_color  "#30f090"

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Mouse Follow the Focus
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

wmname LG3D

# Polybar
#$HOME/dotfiles/polybar/launch.sh --forest

xmobar -A 180 /home/gargula/dotfiles/xmobar/xmobarrc &
trayer --edge top --align right --transparent true --SetDockType true  --alpha 255 --height 30 --distance 0 --margin 10 --widthtype request --SetPartialStrut true --expand true &

$HOME/dotfiles/bspwm/autostart.sh &

