#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor DP-0 -d I II II IV
bspc monitor DP-0 -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           30
bspc config focused_border_color  "#30f090"

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Mouse Follow the Focus
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

wmname LG3D

setxkbmap br 
xsetroot -cursor_name left_ptr &

# Auto start apps
/home/gargula/dotfiles/bin/nvidia-fan.sh &
copyq --start-server &
picom --daemon &
nitrogen --restore & 
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
insync start &
blueman-applet &
nm-applet &
eww open bar &
#xmobar -v -A 180 $HOME/dotfiles/xmobar/xmobarrc 
#trayer --edge top --align right --transparent true --tint 0x00000000 --SetDockType true  --alpha 200 --height 30 --distance 0 --margin 10 --widthtype request --SetPartialStrut true --expand true &




