password = [
    48,
    48,
    120,
    70,
    43,
    101,
    110,
    100,
    55,
    88,
    71,
    89,
    50,
    101,
    111,
    74,
    85,
    65,
    48,
    117,
    103,
    70,
    119,
    82,
    103,
    87,
    54,
    52,
    104,
    88,
    108,
    77,
    88,
    75,
    101,
    97,
    71,
    82,
    68,
    111,
    98,
    119,
    122,
    84,
    110,
    122,
    99,
    121,
    101,
    121,
    114,
    114,
    70,
    43,
    110,
    53,
    120,
    54,
    71,
    50,
    47,
    70,
    55,
    75,
    105,
    107,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'custom'
custom_image_quality = [100]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable_file_transfer = false
show_quality_monitor = false
keyboard_mode = 'map'
view_only = false

[options]
codec-preference = 'auto'
zoom-cursor = ''
touch-mode = ''
custom-fps = '70'

[ui_flutter]
wm_RemoteDesktop = '{"width":0.0,"height":0.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'

[info]
username = 'gargula'
hostname = 'zorinos'
platform = 'Linux'

[transfer]
write_jobs = []
read_jobs = []
