password = [
    48,
    48,
    52,
    66,
    118,
    118,
    53,
    100,
    55,
    88,
    78,
    79,
    85,
    80,
    106,
    50,
    97,
    111,
    116,
    120,
    104,
    101,
    108,
    104,
    49,
    81,
    104,
    57,
    119,
    119,
    114,
    84,
    68,
    104,
    65,
    101,
    122,
    107,
    116,
    103,
    118,
    98,
    53,
    52,
    88,
    51,
    101,
    72,
    115,
    103,
    87,
    75,
    84,
    67,
    109,
    89,
    77,
    104,
    100,
    118,
    122,
    119,
    111,
    88,
    112,
    109,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'best'
custom_image_quality = [100]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable_file_transfer = false
show_quality_monitor = false
keyboard_mode = 'map'
view_only = false

[options]
custom-fps = '60'
zoom-cursor = ''
codec-preference = 'h265'
touch-mode = ''

[ui_flutter]
wm_RemoteDesktop = '{"width":0.0,"height":0.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'

[info]
username = 'gargula'
hostname = 'linuxmint'
platform = 'Linux'

[transfer]
write_jobs = []
read_jobs = []
