remote_id = '6051026'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-left = '0.0'
remote-menubar-drag-right = '1.0'
theme = 'dark'

[ui_flutter]
peer-sorting = 'Remote ID'
wm_PortForward = '{"width":626.0,"height":1012.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
wm_FileTransfer = '{"width":626.0,"height":1012.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
wm_RemoteDesktop = '{"width":626.0,"height":1012.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
wm_Main = '{"width":819.0,"height":499.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
wm_Unknown = '{"width":626.0,"height":1012.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
remoteMenubarState = '{"pin":true}'
